title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://minxola.github.io/road/
baseurl: "/road"
paginate_path: "/road/blog/page:num/"
permalink: /road/blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /road/index.html
  - title: About
    url: /road/about
  - title: Contact
    url: /road/contact

social:
  github: minxola
  twitter: texellabs
  facebook: texellabs
  email: texellabs@gmail.com

google_analytics: "UA-58263416-1"
